/** @type {import('tailwindcss').Config} */
module.exports = {
   mode: 'jit',
   content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      '.components/components/**/*.{js,ts,jsx,tsx}',
   ],
   theme: {
	extend: {
	   colors: {
		  'app-color-primary': 'var(--color-primary)',
		  'app-color-primary-05': 'var(--color-primary-05)',
		  'app-color-primary-01': 'var(--color-primary-01)',
		  'app-color-secondary': 'var(--color-secondary)',
		  'app-color-secondary-02': 'var(--color-secondary-02)',
		  'app-color-texts': 'var(--color-texts)',
		  'app-color-background': 'var(--color-background)',
		  'app-color-background-light': 'var(--color-background-light)',
		  'app-color-black': 'var(--color-black)',
		  'app-color-black-08': 'var(--color-black-08)',
		  'app-color-black-06': 'var(--color-black-06)',
		  'app-color-white': 'var(--color-white)',
		  'app-color-white-09': 'var(--color-white-09)',
	   },
	   margin: {
		  'app-margin-4': 'var(--spacing-4)',
		  'app-margin-8': 'var(--spacing-8)',
		  'app-margin-10': 'var(--spacing-10)',
		  'app-margin-12': 'var(--spacing-12)',
		  'app-margin-16': 'var(--spacing-16)',
		  'app-margin-20': 'var(--spacing-20)',
		  'app-margin-24': 'var(--spacing-24)',
		  'app-margin-30': 'var(--spacing-30)',
		  'app-margin-32': 'var(--spacing-32)',
		  'app-margin-40': 'var(--spacing-40)',
		  'app-margin-50': 'var(--spacing-50)',
		  'app-margin-60': 'var(--spacing-60)',
		  'app-margin-80': 'var(--spacing-80)',
		  'app-margin-100': 'var(--spacing-100)',
		  'app-margin-120': 'var(--spacing-120)',
	   },
	   padding: {
		  'app-padding-4': 'var(--spacing-4)',
		  'app-padding-8': 'var(--spacing-8)',
		  'app-padding-10': 'var(--spacing-10)',
		  'app-padding-12': 'var(--spacing-12)',
		  'app-padding-16': 'var(--spacing-16)',
		  'app-padding-20': 'var(--spacing-20)',
		  'app-padding-24': 'var(--spacing-24)',
		  'app-padding-32': 'var(--spacing-32)',
		  'app-padding-40': 'var(--spacing-40)',
		  'app-padding-60': 'var(--spacing-60)',
		  'app-padding-80': 'var(--spacing-80)',
		  'app-padding-90': 'var(--spacing-90)',
		  'app-padding-100': 'var(--spacing-100)',
		  'app-padding-120': 'var(--spacing-120)',
	   },
	   fontSize: {
		  'app-font-10': 'var(--font-10)',
		  'app-font-12': 'var(--font-12)',
		  'app-font-14': 'var(--font-14)',
		  'app-font-15': 'var(--font-15)',
		  'app-font-16': 'var(--font-16)',
		  'app-font-18': 'var(--font-18)',
		  'app-font-20': 'var(--font-20)',
		  'app-font-22': 'var(--font-22)',
		  'app-font-24': 'var(--font-24)',
		  'app-font-26': 'var(--font-26)',
		  'app-font-30': 'var(--font-30)',
		  'app-font-40': 'var(--font-40)',
		  'app-font-48': 'var(--font-48)',
		  'app-font-50': 'var(--font-50)',
	   },
	   fontWeight: {
		  'app-font-weight-700': 'var(--font-weight-700)',
	   },
	   fontFamily: {
		  'app-font-poppins': 'var(--font-poppins)',
		  'app-font-poppins-bold': 'var(--font-poppins-bold)',
		  'app-font-montserrat': 'var(--font-montserrat)',
		  'app-font-montserrat-bold': 'var(--font-montserrat-bold)',
		  'app-font-avenir': 'var(--font-avenir)',
	   },
	   borderRadius: {
		  'app-border-radius-1.5': 'var(--border-radius-one-point-five)',
		  'app-border-radius-2': 'var(--border-radius-2)',
		  'app-border-radius-10': 'var(--border-radius-10)',
		  'app-border-radius-20': 'var(--border-radius-20)',
	   },
	   borderWidth: {
		  'app-border-radius-one-point-five':
			 'var(--border-radius-one-point-five)',
		  'app-border-radius-2': 'var(--border-radius-2)',
	   },
	   screens: {
		  'app-min-width-extra-small': {min: '480px'},
		  'app-min-width-small': {min: '769px'},
		  'app-min-width-medium': {min: '1025'},
		  'app-min-width-large': {min: '1601'},
		  'app-max-width-extra-small': {max: '479px'},
		  'app-max-width-small': {max: '768px'},
		  'app-max-width-medium': {max: '1024px'},
		  'app-max-width-large': {max: '1600px'},
	   },
	},
 },
   plugins: [],
};
